### ISSUE TITLE
Envoi de mail => deliverd.getSmtpClient => dial tcp IP:25: invalid argument

### ISSUE THREAD

**Issue by maiko** [Toorop/tmail-bugtracker#1]
Bonsoir Stéphane, 

Je test actuellement tmail et je rencontre un souci : tmail ne parvient pas à envoyer de mail vers l'extérieur. J'ai testé l'envoi vers un exchange hosted OVH et un serveur OVH, quel que soit la destination en fait. 

Dans les logs j'ai ceci : 

[philae.dnet.ovh - 127.0.0.1] 2015/04/27 22:54:52.751272 DEBUG - deliverd-remote:  &[{0  {127.0.0.1 false} ex.mail.ovh.net. {25 true} {1 true} { false} { false} { false} { false}}] <nil>
[philae.dnet.ovh - 127.0.0.1] 2015/04/27 22:54:52.760377 DEBUG - deliverd.getSmtpClient: unable to get a client 127.0.0.1 -> 188.165.185.33 : 25 - dial tcp 188.165.185.33:25: invalid argument
[philae.dnet.ovh - 127.0.0.1] 2015/04/27 22:54:52.760454 INFO - deliverd ae79a2211ee57809bc201b99f569241174809738: temp failure - unable to get client

Un peu plus de ligne dispo à cette adresse : https://philae.dnet.ovh/paste/?d7b40e222d9ed8b8b9#QrPZ0ZJG7rvNSEy9BBzN67tnFLA+FGgj4lcD+ZaDYOI=

J'utilise tmail en dernière version disponible sur tmail.io + dovecot 2.2.13 + sieve. 

S'agit-il d'un bug ? Une idée d'où pourrait provenir le problème le cas échéant ? 

Merci,
Maiko

**Comment by Toorop** [comment]
D'après le logs, tmail n'arrive pas ça établir une connexion SMTP. 
A priori tu as configuré l'IP locale sur 127.0.0.1, dans le fichier de config change TMAIL_DELIVERD_LOCAL_IPS pour y mettre une IP routable.

**Comment by maiko** [comment]
Bonjour,

C'était bien ça oui ! Merci !

Le fichier de conf est pas forcément très explicite du coup puisqu'il est question d'IP locale et l'exemple est en 127.0.0 ;)

Merci encore,
Maiko
